version: '3'

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: sr-rest-dev
    ports:
      - '8080:8080'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sr-client-dev
    volumes:
      #- '.:/app'
      - '/app/node_modules'
      - './client:/app'
      #- './client:/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - web
    command: npm start